services:
  wordpress:
    build:
      context: ./docker
    # image: wordpress:latest
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      BNA_AWS_REGION: ${BNA_AWS_REGION}
      BNA_AWS_ACCESS_KEY_ID: ${BNA_AWS_ACCESS_KEY_ID}
      BNA_AWS_SECRET_ACCESS_KEY: ${BNA_AWS_SECRET_ACCESS_KEY}
      BNA_AWS_SQS_QUEUE_URL: ${BNA_AWS_SQS_QUEUE_URL}
    volumes:
      - ./plugin:/var/www/html/wp-content/plugins
      - ./wp-config.php:/var/www/html/wp-config.php
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress

volumes:
  db_data:
